eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/dhl_microservice?stringtype=unspecified
    password: root
    username: postgres

  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          issuer-uri: http://20.219.56.2:30435/auth/realms/nagarro_cdcp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: cdcp
      principal-attribute: preferred_username
